theme: jekyll-theme-minimal
title: Weather Forecast React App
description: a convenient app to show people the weather forecast for the next 5 days. Below is a sample of the forecast data that your app will use.
